### ISSUE TITLE
Move to Github Action

### ISSUE THREAD

**Issue by x86chi** [x86chi/jejunu-bob-pwa#63]
지금 프로젝트는 yarn 으로 구성되어 있는데, CircleCI 설정은 패키지 매니져로 npm 을 쓰고 있다. 😓 

#62 머지 후 수정하는 김에 깃헙 액션으로 옮기자

```yml
name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn
      - name: Type Check
        run: yarn tsc --noEmit
        run: yarn service-worker
```
